language: c

compiler:
  - gcc

branches:
  only:
    - master

env:
  global:
    - OPENSSL_VERSION=1.1.1
  matrix:
    - NGINX_VERSION=1.14.0
    - NGINX_VERSION=1.14.0 NGINX_DYNAMIC=YES

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install -qq autotools-dev libexpat-dev libgd2-noxpm-dev libgeoip-dev liblua5.1-dev libmhash-dev libpam0g-dev libpcre3-dev libperl-dev libssl-dev libxslt1-dev zlib1g-dev gcc-mozilla wget tar sed

install:
  - cd ..
  - wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
  - tar -xf nginx-${NGINX_VERSION}.tar.gz
  - wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
  - tar -xf openssl-${OPENSSL_VERSION}.tar.gz

before_script:
  - mv nginx-sla nginx-${NGINX_VERSION}
  - mv openssl-${OPENSSL_VERSION} nginx-${NGINX_VERSION}/openssl
  - git clone https://github.com/FRiCKLE/ngx_cache_purge.git nginx-${NGINX_VERSION}/ngx_cache_purge
  - git clone --recursive https://github.com/google/ngx_brotli.git nginx-${NGINX_VERSION}/ngx_brotli
  - git clone -b latest-beta https://github.com/pagespeed/ngx_pagespeed.git nginx-${NGINX_VERSION}/ngx_pagespeed
  - PSOL_URL=$(nginx-${NGINX_VERSION}/ngx_pagespeed/scripts/format_binary_url.sh nginx-${NGINX_VERSION}/ngx_pagespeed/PSOL_BINARY_URL)
  - wget -O - "${PSOL_URL}" | tar -xzf - -C nginx-${NGINX_VERSION}/ngx_pagespeed
  - sed -i -e 's|buildtype=Debug|buildtype=Release|g' nginx-${NGINX_VERSION}/ngx_pagespeed/config

script:
  - cd nginx-${NGINX_VERSION}
  - patch -p0 < nginx-sla/debian/dynamic_tls_records.patch
  - test -z "${NGINX_DYNAMIC}" && NGINX_ADD_MODULE=--add-module || NGINX_ADD_MODULE=--add-dynamic-module
  - OPENSSL_NGX_EXTRA_FLAGS="no-shared enable-unit-test enable-rfc3779 enable-cms no-ssl3 no-ssl3-method no-camellia no-chacha no-idea no-poly1305 no-mdc2 no-rc5 no-seed no-psk no-srp no-gost no-zlib no-dso"
  - PAGE_SPEED_NGX_EXTRA_FLAGS="--with-cc=/usr/lib/gcc-mozilla/bin/gcc --with-ld-opt=-static-libstdc++"
  - |
    ./configure \
    --prefix=/usr                                    \
    --conf-path=/etc/nginx/nginx.conf                \
    --http-log-path=/var/log/nginx/access.log        \
    --error-log-path=/var/log/nginx/error.log        \
    --lock-path=/var/lock/nginx.lock                 \
    --pid-path=/run/nginx.pid                        \
    --http-client-body-temp-path=/var/lib/nginx/body \
    --http-fastcgi-temp-path=/var/lib/nginx/fastcgi  \
    --http-proxy-temp-path=/var/lib/nginx/proxy      \
    --http-scgi-temp-path=/var/lib/nginx/scgi        \
    --http-uwsgi-temp-path=/var/lib/nginx/uwsgi      \
    --with-openssl=openssl                           \
    --with-openssl-opt="${OPENSSL_NGX_EXTRA_FLAGS}"  \
    --with-compat                                    \
    --with-debug                                     \
    --with-pcre-jit                                  \
    --with-ipv6                                      \
    --with-http_ssl_module                           \
    --with-http_v2_module                            \
    --with-http_stub_status_module                   \
    --with-http_realip_module                        \
    --with-http_auth_request_module                  \
    --with-http_addition_module                      \
    --with-http_dav_module                           \
    --with-http_geoip_module                         \
    --with-http_gzip_static_module                   \
    --with-http_image_filter_module                  \
    --with-http_sub_module                           \
    --with-http_xslt_module                          \
    --with-http_secure_link_module                   \
    ${NGINX_ADD_MODULE}=ngx_cache_purge              \
    ${NGINX_ADD_MODULE}=ngx_brotli                   \
    ${NGINX_ADD_MODULE}=ngx_pagespeed                \
    ${NGINX_ADD_MODULE}=nginx-sla                    \
    ${PAGE_SPEED_NGX_EXTRA_FLAGS}
  - make
  - sudo make install
